runtime: nodejs18
env: standard

instance_class: F1
automatic_scaling:
  min_instances: 1
  max_instances: 1

handlers:
  - url: /v1/.*
    script: auto
    secure: always

env_variables:
  NODE_ENV: production
